# Generated by Django 5.0.6 on 2024-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_age_alter_customuser_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified_at',
            field=models.BooleanField(default=False, verbose_name='email verified at'),
        ),
    ]
