# Generated by Django 5.0.6 on 2024-07-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified_at',
            new_name='email_verified',
        ),
    ]
