# Generated by Django 5.0.6 on 2024-07-15 03:36

import django.core.validators
import django.db.models.deletion
import nagoyameshi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='論理削除日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='曜日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('name', models.CharField(max_length=15, verbose_name='カテゴリ名')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('name', models.CharField(max_length=30, verbose_name='店舗名')),
                ('description', models.CharField(max_length=500, verbose_name='店舗説明')),
                ('image', models.ImageField(blank=True, default='nagoyameshi/noimage.png', upload_to=nagoyameshi.models.get_top_image_path, verbose_name='トップ画像')),
                ('floor_price', models.PositiveIntegerField(verbose_name='下限価格')),
                ('maximum_price', models.PositiveIntegerField(verbose_name='上限価格')),
                ('opening_time', models.TimeField(verbose_name='開店時刻')),
                ('closing_time', models.TimeField(verbose_name='閉店時刻')),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^[0-9]{3}-[0-9]{4}$')], verbose_name='郵便番号')),
                ('city', models.CharField(max_length=50, verbose_name='市区町村')),
                ('street_address', models.CharField(max_length=50, verbose_name='番地以降住所')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10,11}$')], verbose_name='電話番号')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nagoyameshi.category', verbose_name='カテゴリー')),
                ('regular_closing_day', models.ManyToManyField(to='nagoyameshi.day', verbose_name='定休日')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('reservation_datetime', models.DateTimeField(verbose_name='予約日時')),
                ('number_of_persons', models.PositiveIntegerField(verbose_name='予約人数')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='コメント')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('image', models.ImageField(upload_to=nagoyameshi.models.get_photos_path, verbose_name='画像')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('number_of_stars', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星の数')),
                ('comment', models.CharField(max_length=800, verbose_name='コメント')),
                ('visited_date', models.DateField(verbose_name='利用日')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗')),
            ],
            options={
                'unique_together': {('user_id', 'restaurant_id')},
            },
        ),
    ]
