# Generated by Django 5.0.6 on 2024-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='key',
            field=models.PositiveIntegerField(default=0, verbose_name='整数値'),
        ),
    ]
